language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH:./node_modules/.bin"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

node_js:
  - 8
script: yarn test
